WITH ARBEIDER AS (
    SELECT
        KU.NAVN,
        KO.PENGER
    FROM
        KUNDER AS KU
        INNER JOIN KODER AS KO ON KO.ID = KO.ID
    WHERE
        KU.TID = '23042020'
)
UPDATE
    STYRING
SET
    S.Generiskstyringsfelt32 = CASE
        WHEN S.SALDO_BELOP >= 5000 THEN 'ARBEIDER_GEB'
        ELSE 'ARBEIDER'
    END
FROM
    STYRING as S
    INNER JOIN ARBEIDER AS A ON A.KUNDENUMMER = S.KUNDENUMMER;
